### ISSUE TITLE
Unable to enter values in questions requiring a time

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#63]
Erin from HP did testing for us for another purpose and had to run through the modules to complete testing.  In the process, she was unable to enter a time in questions requiring it.  See screenshot below.  Entering this GitHub issue to make sure we test this in the next round.

![Screen Shot 2022-04-07 at 12 07 23 PM](https://user-images.githubusercontent.com/83971268/162287773-4dda6971-0a3e-49ff-a3ff-bfc166e1f756.png)

**Comment by FrogGirl1123** [comment]
Assigning Davin and Brian in case this is a PWA issue.  Keeping Jen in the loop, in case this is something we need IMS to help us test.

**Comment by cunnaneaq** [comment]
I just tested module 2 on a tablet to see if I could replicate Erin's issue.  I see the same gray line as she does, in these questions, but if you click on the gray line a drop down appears where you can enter the time (see screenshots below).  It works, and you can enter a time, but I see how this could be misleading to participants.  It doesn't look like this when I complete module 2 on my laptop.

![My Connect - Dashboard](https://user-images.githubusercontent.com/83971268/162826672-efd0e971-e597-41fc-bc21-eceb0bb43448.png)

![image0](https://user-images.githubusercontent.com/83971268/162826460-1d6e38b4-dc2a-47b1-80ec-3c2a2f8b973b.png)

**Comment by naiyume** [comment]
@cunnaneaq this should be fixed on the pwa side for now. Please let me know if you continue to run into this issue.

**Comment by cunnaneaq** [comment]
@naiyume checked this today, and still seeing the same thing on my iPad

**Comment by cusackjm** [comment]
@cunnaneaq i dont see the gray box, does this have to do with me testing on a desktop PC?

**Comment by cunnaneaq** [comment]
@cusackjm yes, the issue only occurs on tablets and phones as far as I've seen.  No issue with the time on a PC.  @naiyume made the size of the box bigger and we discussed leaving it as is for now until the higher priority issues are taken care of, since participants are able to enter a time if they click on the box.

**Comment by naiyume** [comment]
The code for the fix is currently not on stage yet if that is where you found this issue.

**Comment by cusackjm** [comment]
@naiyume ok that was where i saw it

**Comment by KELSEYDOWLING7** [comment]
Was able to enter times for all questions on 6/2 testing

**Comment by danielruss** [comment]
@naiyume   Would setting a default value solve the problem?

Try:
```
[HELLO] Hi what time do you wake up |time|value=08:00|

[END] This is the END
```

**Comment by danielruss** [comment]
on my android phone:

<img width="431" alt="screenshot" src="https://user-images.githubusercontent.com/3767675/175332446-c118f0bf-cb3a-4522-ac3a-1560e02f3850.png">

**Comment by cusackjm** [comment]
@boyd-mj The NCI team has decided to add additional question text (If you are using a phone or tablet, please tap the gray box to enter your response) to Module 2 (SLEEP1A, SLEEP1F, SLEEP2A, SLEEP2F, SHIFTWORK2, SHIFTWORK5) and the biospecimen qx (EATDRINKTIME, SLEEPTIME, WAKETIME).

The question text has been added and is denoted in tracked changes.

**Comment by huip-ims** [comment]
@cusackjm Hi Julie - In the quex Word document, I noticed the additional question text is underlined. Can you please confirm whether or not the added text "If you are using a phone or tablet, please tap the gray box to enter your response" should be underlined?

**Comment by guinevere83** [comment]
These changes have passed internal testing and are ready for delivery.

**Comment by cusackjm** [comment]
Confirmed fixed for Module 2 in testing on 8/2 (removing Mod2 tag)
Waiting on biospecimen delivery

**Comment by cusackjm** [comment]
fixed in testing on 9/30
