### ISSUE TITLE
Missing Headings in Module 1

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#87]
* aesthetic issues to be updated at a later date

Module 1 Missing Headings:
- "Depression" Should be on same page as [DEPRESSINTRO]
- [SECTION 4] "Family History" Heading should be on same page as [FAMHISTINTRO]

**Comment by boyd-mj** [comment]
This issue has been fixed and will be included in the next delivery

**Comment by boyd-mj** [comment]
Delivered

**Comment by KELSEYDOWLING7** [comment]
Still seeing "Depression" header missing on 5/23/testing for Connect_ID 4164883179 (Test Scenario 3). 
"Family History" was added successfully

**Comment by cusackjm** [comment]
confirmed fix tommytesterdceg@gmail.com on 5/26
