### ISSUE TITLE
Formatting for text boxes is on same line as text

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#88]
Text box should be on a different line from the supporting response text for CHILD and SIB's cancer date of dx questions 
![image](https://user-images.githubusercontent.com/85582895/167186507-54b21caf-e49e-43bd-9403-246d16a81131.png)

**Comment by cusackjm** [comment]
Should look like this:
![image](https://user-images.githubusercontent.com/85582895/167198354-11d267de-4a6b-47a0-9b2e-a15e285a6d90.png)

**Comment by cusackjm** [comment]
markup issue

**Comment by boyd-mj** [comment]
Delivered

**Comment by cusackjm** [comment]
want to reopen for retest to confirm fix

**Comment by cusackjm** [comment]
still there on 5/26 for WEIGHT 
![image](https://user-images.githubusercontent.com/85582895/170564070-6195955d-4432-4d4c-8c70-2f559cd7f035.png)

**Comment by cusackjm** [comment]
@boyd-mj what is the status on this?

**Comment by boyd-mj** [comment]
@cusackjm I just assigned this for someone to take a look at. I apologize - I don't think we realized the issue had been reopened/reassigned to us.

**Comment by boyd-mj** [comment]
This issue has been fixed

**Comment by cusackjm** [comment]
still present in testing on 7/12 for SIBNAME
(this happened when I hit next, then went back)
![image](https://user-images.githubusercontent.com/85582895/178582696-5766c1ff-1964-465c-9a33-6e68afa1d168.png)

**Comment by boyd-mj** [comment]
@joshid-ims @huip-ims could one of you please reopen our Squish issue for this?

@cusackjm could you please tag Pete and Deepti when you refer issues that we've delivered back to us? They are monitoring Github to make sure issues get added to our list as quickly as possible. Thanks!

**Comment by boyd-mj** [comment]
@naiyume any response to Gwen's question above?

**Comment by cusackjm** [comment]
@naiyume saw this for ECIG10
![image](https://user-images.githubusercontent.com/85582895/180826704-f4d1421a-dfd9-422e-9411-3886a2f1d12a.png)

**Comment by cusackjm** [comment]
@danielruss is this a code issue

**Comment by danielruss** [comment]
@cusackjm is the question about spacing around Brand/Model and the text box?

**Comment by danielruss** [comment]
@cusackjm  Not really a code error.  It more like a design error.  I need to think about how to solve the problem.  I'm happy to have a call with anyone to discuss the problem.  The issue deals with trying to decide whether the user wants a new line or not.  Remember the problem where there was WAY too much space.  Well we over fixed it.  There are two workarounds that I know of.  

1.  Add more new lines (hit return at least twice).  That forces the new lines.
2. Add a P tag (<p>) this will force a new paragraph.  You can go crazy with this option, so I advise the other workaround.

```
[ECIG10?,displayif=equals(TOBACCO,1)] What brand and model of device |displayif=doesNotExist("ECIG5") or valueEquals("ECIG5",0)|do||displayif=valueIsOneOf("ECIG5",1,2)|did| you use most often?


Device Brand/Model 1 |__|
<p>Device Brand/Model 2 |__|</p>
<p style="padding-top:1cm;padding-bottom:1cm;background-color:red">Device Brand/Model 3|__|</p>
```

<img width="800" alt="image" src="https://user-images.githubusercontent.com/3767675/181543793-6bf552df-917c-464f-97cd-964622219241.png">

**Comment by huip-ims** [comment]
@danielruss @boyd-mj @cusackjm Hi Julie - We’ve been doing some additional testing on this issue, and here’s what we’ve noticed.

On questions without any Displayif or piped text (MOMAGE, MOMDEATH, DADAGE, DADDEATH), simply adding a new line (i.e., hit ‘Enter’ at the end of the markup code line) will work as expected. The text box is displayed on the next line, and going back and forward screen will not cause any spacing issues. However, on questions with Displayif and/or piped text, the new line command is ignored by the renderer/PWA, and the text box is now displayed on the same line as the text.

Using Daniel’s suggestion of adding additional new lines (i.e., hit the ‘Enter’ button multiple times or use multiple forced line breaks `<br/>`) at the end of the markup code line, this results in only a temporary fix.  Each time you do a back and forward screen sequence, it will negate one of the added line breaks in the markup code. Therefore, it you do enough times of the back and forward screen sequence, eventually, the text box will be back on the same line as the text.

The only option from Daniel’s suggestions that appears to work is the forced paragraph `</p>`. Doing the back and forward screen sequence did not seem to affect the forced paragraph command. The issue with this command is it adds 2 lines between the text and the text box, so the spacing looks off (see attached image below).  If this double line skip is acceptable to NCI, we can proceed to implement this on SIBAGE, SIBDEATH, CHILDAGE, and CHILDDEATH, which I think are the only questions remaining in Module 1 with this text box spacing issue. Let me know if you would like proceed with this change, and if so, what additional questions you’ve identified that need this fix, whether in Module 1 or any other modules.

![image](https://user-images.githubusercontent.com/82978291/182680038-3fc88929-110e-4602-8fd8-d2b2b8d74bdf.png)

**Comment by huip-ims** [comment]
@cusackjm Hi Julie - have you had a chance to review my comment and decide if you would like to proceed with the forced paragraph option?

**Comment by cusackjm** [comment]
fixed in 9/8 testing for mod 1

**Comment by cunnaneaq** [comment]
@danielruss @cusackjm Did not see this issue in mod 3 in stage testing 9/28

**Comment by danielruss** [comment]
so ok to close?

**Comment by cunnaneaq** [comment]
yes
